### ISSUE TITLE
Failure to install local collection or role

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/ansible-compat#65]
When handling a role that's inside of a collection, ansible-compat is unable to determine that the collection exists. Therefore, it errors because a role name and namespace are not specified inside of `meta/main.yml`. [Here](https://github.com/oasis-roles/ansible_collection_system/pull/54/checks?check_run_id=3475530293) is an example CI run where this occurs.

**Comment by ssbarnea** [comment]
`meta.main.yml` has nothing to do with that but the bug report is valid. At this moment the local collection is not installed so code trying to make use of the collection will fail. We will need to make several patches in order to implement this missing feature.

A collection presence will be determined by the presence of `galaxy.yml` in current directory. We are not yet sure if we want to make the local collection detection and installation implicit for `Runtime()` as as some consumers may not want this feature.

I am curious what @tadeboro and @webknjaz think about this. We could add a parameter (what name?) to either `Runtime()` constructor or the `Runtime.prepare_environment()` which would enable or disable the installation of local code (collection, maybe role for standalone roles). 

If we do this, what should be the default behavior install it if detected or not doing anything?
